#!/bin/bash
#
# Copyright 2013 David Edwards
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

__BASE_DIR=$(cd $(dirname $0)/..; pwd)
. "$__BASE_DIR"/bin/setenv.sh
__CLASSPATH=$(echo $__BASE_DIR/lib/*.jar | sed "s/ /:/g")
__CLASS=com.loopfor.zookeeper.cli.CLI
$__JAVA $JAVA_OPTS $SCALA_OPTS -classpath $__CLASSPATH $__CLASS "$@"
